#!/bin/sh
set -e

if [ $# != 2 ] ; then
	echo >&2 "Usage: $0 <source> <target>"
	exit 1
fi

sed <"$1" >"$2" "
	s/@TODAY@/$DATE/
	s/@VERSION@/pciutils-$VERSION/
	s#@IDSDIR@#$IDSDIR#
	s#@PCI_IDS@#$PCI_IDS#
"
